spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate Properties (validate schema against entity, we created it manually)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JWT Application properties
todoapp.app.jwtSecret=TodoAppSecretKeyForJwtWhichMustBeLongEnoughToGenerateAValidKeyForHS256Algorithm
todoapp.app.jwtExpirationMs=86400000

# Server port
server.port=8080
